import{chromium,expect}from'@playwright/test';
import fs from'node:fs/promises';
await fs.mkdir('qa/screenshots',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1568,height:900}});const errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const goto=async route=>{await page.goto(`http://localhost:5173/#/${route}`);await page.waitForFunction(()=>!document.body.dataset.opening);await page.waitForTimeout(300);if(['about','archive'].includes(route))await page.waitForFunction(()=>document.querySelector('.stage')?.dataset.revealState==='complete');};
try{
await goto('cover');await expect(page).toHaveTitle('曹雨晨的PORTFOLIO');await page.locator('.cover-open').click();await expect(page).toHaveURL(/#\/choose$/);checks.push('Cover opens Choose');
for(const key of ['home','about','content']){await goto('choose');const route={home:'cover',about:'about',content:'archive'}[key];await page.locator('.nav-'+key).focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(new RegExp('#/'+route+'$'));}checks.push('All folder navigation routes');
await goto('archive');const obj=page.locator('[data-project="woodlab"]');const before=await obj.boundingBox();await page.mouse.move(before.x+before.width*.5,before.y+before.height*.3);await page.mouse.down();await page.mouse.move(before.x+before.width*.5+80,before.y+before.height*.3-70,{steps:8});await page.mouse.up();const saved=await obj.evaluate(e=>({left:e.style.left,top:e.style.top}));await obj.dblclick({position:{x:80,y:80}});await expect(page).toHaveURL(/project\/woodlab/);await expect(page.locator('.page-counter')).toHaveText('01–02 / 10');await page.keyboard.press('ArrowRight');await expect(page.locator('.page-counter')).toHaveText('03–04 / 10');await page.keyboard.press('ArrowLeft');await expect(page.locator('.page-counter')).toHaveText('01–02 / 10');await page.keyboard.press('Escape');await expect(page).toHaveURL(/#\/archive$/);expect(await page.locator('[data-project="woodlab"]').evaluate(e=>({left:e.style.left,top:e.style.top}))).toEqual(saved);checks.push('Archive drag, z-index, double click, return persistence, book keyboard');
for(const id of ['pawtern','woodlab','nuofield','beeflow']){await goto('project/'+id);await expect(page.locator('.flipbook')).toBeVisible();expect(await page.locator('.project-external').getAttribute('href')).toMatch(/^https:\/\//);await expect(page.locator('.cover-underlay')).toBeVisible();await expect(page.locator('.book-spine')).toBeVisible();await page.locator('.next').click();await page.waitForTimeout(800);await page.locator('.prev').click();await page.waitForTimeout(800);}checks.push('All 4 books have layers, working controls and external URLs');
await goto('other');for(const k of ['A','B','C','D']){await page.locator('.label-'+k).click();await expect(page.locator('.label-'+k)).toHaveAttribute('aria-expanded','true');await page.waitForTimeout(650);expect(await page.locator('.stage').evaluate(e=>e.offsetHeight)).toBe(1510);for(const l of ['A','B','C','D'])await expect(page.locator('.label-'+l)).toBeVisible();await expect(page.locator('#gallery-'+k+' .strip-image').first()).toBeVisible();}await page.locator('.label-D').click();expect(await page.locator('.stage').evaluate(e=>e.offsetHeight)).toBe(900);checks.push('Other A/B/C/D expansion, persistent labels, collapse');
await page.locator('.label-A').click();const track=page.locator('#gallery-A .strip-track');await page.mouse.move(5,5);await page.waitForTimeout(900);const moving=await track.evaluate(e=>getComputedStyle(e).transform);await page.waitForTimeout(400);expect(await track.evaluate(e=>getComputedStyle(e).transform)).not.toBe(moving);await page.locator('#gallery-A .strip-window').hover();await page.waitForTimeout(100);const stopped=await track.evaluate(e=>getComputedStyle(e).transform);await page.waitForTimeout(400);expect(await track.evaluate(e=>getComputedStyle(e).transform)).toBe(stopped);checks.push('Strip constant scrolling and hover pause');
for(const [w,h]of [[1920,1080],[1440,900],[1366,768],[1024,768],[844,390]]){await page.setViewportSize({width:w,height:h});for(const route of ['cover','choose','about','archive']){await goto(route);const r=await page.locator('.stage-shell').boundingBox();expect(r.x).toBeGreaterThanOrEqual(-1);expect(r.y+await page.evaluate(()=>scrollY)).toBeGreaterThanOrEqual(-1);expect(r.x+r.width).toBeLessThanOrEqual(w+1);expect(r.x).toBeLessThanOrEqual(1);expect(r.width).toBeGreaterThanOrEqual(w-20);expect(r.height/r.width).toBeCloseTo(900/1568,3);}await goto('project/pawtern');expect(await page.locator('.book-shell').evaluate(e=>e.classList.contains('single-page'))).toBe(w<1024);await page.screenshot({path:`qa/screenshots/book-${w}x${h}.png`});}checks.push('1920×1080, 1440×900, 1366×768, iPad 1024×768, phone 844×390');
for(const [w,h]of [[390,844],[768,1024]]){await page.setViewportSize({width:w,height:h});await goto('cover');await expect(page.locator('#orientation-message')).toBeVisible();await expect(page.locator('#app')).toBeHidden();}checks.push('Phone and iPad portrait gate');
await page.setViewportSize({width:1440,height:900});await page.emulateMedia({reducedMotion:'reduce'});await goto('project/beeflow');await page.keyboard.press('ArrowRight');await expect(page.locator('.page-counter')).toHaveText('03–04 / 8');checks.push('Reduced-motion book turning');
expect(errors).toEqual([]);
}finally{await fs.writeFile('qa/verification.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));await browser.close();}
